:demo-page: https://MY-USER.github.io/tw5-MY-PLUGIN/
:json: https://MY-USER.github.io/tw5-MY-PLUGIN/tw5-MY-PLUGIN.json

= Plugin template repository for TiddlyWiki 5

*UNDER DEVELOPENT: THE TEMPLATE IS NOT COMPLETE, DO NOT USE IT*

A kickstart for your plugin development. Just fork this repository and change
the contents to your needs.

=== Search for these strings to replace

MY-USER::
Your GitHub user name (https://github.com/MY-USER/), same as your "TiddlyWiki
username" (`$:/plugins/MY-USER/MY-PLUGIN`).

MY-PLUGIN::
Name of the plugin, it's the same as the repository name without `tw5-` prefix
(https://github.com/MY-USER/tw5-MY-PLUGIN/).

=== Files of the plugin

README.adoc (this file)::
Main description, shown in the front page of the repository.

test/tiddlers/tests/::
Test files.

*Template starts here:*

'''

= MY-PLUGIN plugin for TiddlyWiki 5

For details, see the link:{demo-page}[demo page].

* https://github.com/MY-USER/tw5-MY-PLUGIN/ (please star if you like the plugin)

== How to install?

=== Drag-n-drop

- Open the link:{demo-page}[demo page]
- Drag-n-drop the plugin tiddler in to your wiki

=== Download as JSON

- Download the link:{json}[JSON archive of the plugin] (_Right click -> Save as_)
- Drag-n-drop the file in to your wiki

=== Copy to directory based (Node.js) wiki

- Clone or download this repository
- Copy the `plugins` directory to the root directory of your wiki

== Development

=== Running tests

*Before running tests, be sure that `plugins` section in `test/tiddlywiki.info`
contains the directory name of your plugin!*

----
$ cd ROOT_OF_THIS_REPO

# Unix-like system
$ export TIDDLYWIKI_PLUGIN_PATH=./plugins
# Windows
$ set TIDDLYWIKI_PLUGIN_PATH=./plugins

$ tiddlywiki test
----
